### ISSUE TITLE
Lierals lead to exception

### ISSUE THREAD

**Issue by jakobbraun** [exasol/postgresql-virtual-schema#14]
Queries like this fail:
```
SELECT 'test' FROM my_virtual_table.
```
with:
```
ETL-5402: JDBC-Client-Error: JDBC SQL Type for column=0 (starting at 0) value=1111 is unknown.
```

The reason for that seems to be that PostgreSQL sets the column type for columns of just literals to unknown.
( [see](https://stackoverflow.com/questions/36013153/postgresql-jdbc-driver-returns-1111-type-for-literals-in-query))

Since in Exasol literal columns have a type, we probably have to add casts in the query rewriting.

**Comment by AnastasiiaSergienko** [comment]
This issue only occurred on the old postgres test container and it's gone after we updated it. So far we don't want to spend more time on it. I'm closing the ticket

**Comment by chiaradiamarcelo** [comment]
> This issue only occurred on the old postgres test container and it's gone after we updated it. So far we don't want to spend more time on it. I'm closing the ticket

@AnastasiiaSergienko Which version is the old container?
