### ISSUE TITLE
Charset Conversion Error

### ISSUE THREAD

**Issue by djamadeus** [exasol/postgresql-virtual-schema#62]
The same issue described and solved here:
https://github.com/exasol/mysql-virtual-schema/issues/26
also exists with this adapter.
ETL-3009: [Column=13 Row=2] [Charset conversion from 'UTF-8' to 'ASCII' failed [Invalid or incomplete multibyte or wide character]] 

Switching back to 9.0.4-release solved the problem for me.

**Comment by redcatbear** [comment]
Version [2.1.0](https://github.com/exasol/postgresql-virtual-schema/releases/tag/2.1.0) is released.

**Comment by djamadeus** [comment]
awesome. will run some teste between holidays and give you feedback.
