### ISSUE TITLE
Documentation on uploading JDBC driver

### ISSUE THREAD

**Issue by allipatev** [exasol/postgresql-virtual-schema#65]
With https://github.com/exasol/postgresql-virtual-schema/commit/61c880a1e7496cdbe95dd32716db4b2e8302d75e User guide in this repo doesn't mention EXAOperation and only refers to EXAOperation-less installations like docker, NGA, SaaS.

Majority of the customers at the moment use installations with EXAOperation and where ExaLoader would not look for drivers in "default/drivers/jdbc/" folder of BucketFS.

Please consider covering the currently most frequently used scenario in the repo documentation.

**Comment by redcatbear** [comment]
Since EXAOperation is being sunsetted, the current documentation is good enough. We unfortunately don't have the capacity for this, especially because we would consequently have to do it for every VS.

**Comment by allipatev** [comment]
Having capacity to break documentation but no capacity to fix it looks a bit strange to me.
