### ISSUE TITLE
Update tests to V8 VSPG

### ISSUE THREAD

**Issue by ckunki** [exasol/postgresql-virtual-schema#68]
Since 2023-06-02 for version 8.18.1 of Exasol database a Docker image is available on [Dockerhub](https://hub.docker.com/layers/exasol/docker-db/8.18.1/images/sha256-33ce379848b9c2d3c0535af46a9e23382f1d3ccf5fc8c27131ba5c3e6e19a065).

The current ticket therefore requests to update the integration tests of VSPG to use version 8.18.1 as latest default version.

Please note sibling-tickets for all [JDBC-based virtual schemas](https://github.com/exasol/virtual-schemas/blob/main/doc/user-guide/dialects.md).

**Comment by pj-spoelders** [comment]
Found a possible bug in the sql compiler for CURRENT_SCHEMA pushdown: 
https://exasol.atlassian.net/browse/SPOT-19716
