### ISSUE TITLE
Check if Postgres can support some of the recently added capabilities

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/postgresql-virtual-schema#9]
## Situation

We have added a few new functions to the common part recently.
We need to check if Postgres could support them. The list of the new function capabilities to check:

FN_BIT_LROTATE
FN_BIT_RROTATE
FN_BIT_LSHIFT
FN_BIT_RSHIFT
FN_FROM_POSIX_TIME
FN_HOUR
FN_INITCAP
FN_AGG_EVERY
FN_AGG_SOME
FN_AGG_MUL_DISTINCT
FN_PRED_IS_JSON
FN_PRED_IS_NOT_JSON
FN_HASHTYPE_MD5
FN_HASHTYPE_SHA1
FN_HASHTYPE_SHA256
FN_HASHTYPE_SHA512
FN_HASHTYPE_TIGER
FN_AGG_MUL
FN_JSON_VALUE
FN_MIN_SCALE
FN_AGG_LISTAGG
FN_AGG_LISTAGG_DISTINCT
FN_AGG_LISTAGG_SEPARATOR
FN_AGG_LISTAGG_ON_OVERFLOW_ERROR
FN_AGG_LISTAGG_ON_OVERFLOW_TRUNCATE
FN_AGG_LISTAGG_ORDER_BY
FN_AGG_COUNT_TUPLE

**Comment by jakobbraun** [comment]
we shoudl wait with this until #13

**Comment by chiaradiamarcelo** [comment]
Closing as the new scalar integration tests provided info on which scalar functions are supported and which ones are not

**Comment by chiaradiamarcelo** [comment]
The list of Scalar Functions has been updated.

The following functions are not supported anymore: 
`MINUTES_BETWEEN, SECONDS_BETWEEN, DAYS_BETWEEN, MONTHS_BETWEEN, HOURS_BETWEEN, UNICODECHR, YEARS_BETWEEN, TO_CHAR, POSIX_TIME, UNICODE, CONCAT, SECOND, INSTR, ROUND`

The following new functions are supported: 
`CURRENT_SCHEMA, INITCAP, SESSION_PARAMETER`
